default:
  api_login_id:  6EG65PSF94
  api_transaction_key:  57Pt3Y9q46gU7w46
  MERCHANT_HASH_VALUE:

DEVELOPMENT:
  API_LOGIN_ID: 7G3y9yxSTs
  API_TRANSACTION_KEY: 543sjU49SdMRN8s6
  MERCHANT_HASH_VALUE:

TEST: 
PRODUCTION:
  API_LOGIN_ID: 6EG65PSF94
  API_TRANSACTION_KEY: 57Pt3Y9q46gU7w46
  MERCHANT_HASH_VALUE:
